// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config'
import { defineConfig } from 'prisma/config'

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    // Prisma v7 Datasource type only supports `url` (and `shadowDatabaseUrl`).
    // The pooled URL is used here for migrate/introspect — the direct URL is
    // handled at the driver-adapter level in lib/prisma.ts.
    url: process.env['DIRECT_URL'] ?? process.env['DATABASE_URL'],
  },
})
